//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Proxy.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetGreeting", ReplyAction="http://tempuri.org/IService1/GetGreetingResponse")]
        string GetGreeting(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetGreeting", ReplyAction="http://tempuri.org/IService1/GetGreetingResponse")]
        System.Threading.Tasks.Task<string> GetGreetingAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddData", ReplyAction="http://tempuri.org/IService1/AddDataResponse")]
        int AddData(int firstNum, int secondNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddData", ReplyAction="http://tempuri.org/IService1/AddDataResponse")]
        System.Threading.Tasks.Task<int> AddDataAsync(int firstNum, int secondNum);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WCF_Proxy.ServiceReference2.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WCF_Proxy.ServiceReference2.IService1>, WCF_Proxy.ServiceReference2.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetGreeting(string name) {
            return base.Channel.GetGreeting(name);
        }
        
        public System.Threading.Tasks.Task<string> GetGreetingAsync(string name) {
            return base.Channel.GetGreetingAsync(name);
        }
        
        public int AddData(int firstNum, int secondNum) {
            return base.Channel.AddData(firstNum, secondNum);
        }
        
        public System.Threading.Tasks.Task<int> AddDataAsync(int firstNum, int secondNum) {
            return base.Channel.AddDataAsync(firstNum, secondNum);
        }
    }
}
